# Generated by Django 3.1.7 on 2021-05-07 16:44

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos', validators=[utils.validators.validate_size, utils.validators.validate_extension], verbose_name='Фото'),
        ),
    ]
