# Generated by Django 3.1.7 on 2021-04-25 17:14

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('age', models.IntegerField(validators=[main.models.age_range_validation], verbose_name='Возраст')),
                ('nationality', models.CharField(max_length=50, verbose_name='Национальность')),
                ('additional_data', models.TextField(blank=True, max_length=500, null=True, verbose_name='Дополнительные сведения')),
                ('contract_terms', models.TextField(max_length=250, verbose_name='Условия контракта')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signing_date', models.DateField(verbose_name='Дата подписания')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания')),
                ('previous_club', models.CharField(blank=True, max_length=100, null=True, verbose_name='Предыдущий клуб')),
                ('salary', models.IntegerField(validators=[main.models.salary_range_validation], verbose_name='Зарплата')),
                ('additional_data', models.TextField(blank=True, max_length=500, null=True, verbose_name='Дополнительные сведения')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('website', models.CharField(max_length=50, verbose_name='Веб сайт')),
            ],
            options={
                'verbose_name': 'Футбольный клуб',
                'verbose_name_plural': 'Футбольные клубы',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(verbose_name='Сыграно матчей')),
                ('yellow_cards', models.IntegerField(verbose_name='Желтые карточки')),
                ('red_cards', models.IntegerField(verbose_name='Красные карточки')),
                ('goals_scored', models.IntegerField(verbose_name='Забитые голы')),
                ('assists', models.IntegerField(verbose_name='Голевые передачи')),
                ('minutes_played', models.IntegerField(verbose_name='Количество сыгранных минут')),
                ('is_injured', models.BooleanField(verbose_name='Травмирован')),
                ('injury_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип трамвы')),
            ],
            options={
                'verbose_name': 'Статистика игрока',
                'verbose_name_plural': 'Статистика игроков',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('openning_date', models.DateField(verbose_name='Дата Открытия')),
                ('capacity', models.IntegerField(validators=[main.models.capacity_range_validation], verbose_name='Вместимость')),
                ('architect', models.CharField(blank=True, max_length=100, null=True, verbose_name='Проектировщик')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Стадион',
                'verbose_name_plural': 'Стадионы',
            },
        ),
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(verbose_name='Сыграно матчей')),
                ('yellow_cards', models.IntegerField(verbose_name='Желтые карточки')),
                ('red_cards', models.IntegerField(verbose_name='Красные карточки')),
                ('goals_scored', models.IntegerField(verbose_name='Забитые голы')),
                ('wins', models.IntegerField(verbose_name='Победы')),
                ('draws', models.IntegerField(verbose_name='Ничьи')),
                ('loses', models.IntegerField(verbose_name='Поражения')),
                ('goals_conceded', models.IntegerField(verbose_name='Пропущенные голы')),
                ('points', models.IntegerField(verbose_name='Количество очков')),
                ('place', models.IntegerField(validators=[main.models.place_range_validation], verbose_name='Место в таблице')),
            ],
            options={
                'verbose_name': 'Статистика клуба',
                'verbose_name_plural': 'Статистика клубов',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('age', models.IntegerField(validators=[main.models.age_range_validation], verbose_name='Возраст')),
                ('nationality', models.CharField(max_length=50, verbose_name='Национальность')),
                ('additional_data', models.TextField(blank=True, max_length=500, null=True, verbose_name='Дополнительные сведения')),
                ('position', models.CharField(max_length=50, verbose_name='Амплуа')),
                ('height', models.IntegerField(blank=True, null=True, validators=[main.models.height_range_validation], verbose_name='Рост')),
                ('weight', models.IntegerField(blank=True, null=True, validators=[main.models.weight_range_validation], verbose_name='Вес')),
                ('shirt_number', models.IntegerField(validators=[main.models.shirt_number_range_validation], verbose_name='Номер')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Веб сайт')),
                ('is_foreign', models.BooleanField(verbose_name='Легионер')),
                ('is_from_academy', models.BooleanField(verbose_name='Воспитанник клуба')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.agent', verbose_name='Агент')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.contract', verbose_name='Контракт')),
                ('football_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.footballclub', verbose_name='Футбольный клуб')),
                ('statistics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.playerstatistics', verbose_name='Статистика игрока')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.CharField(blank=True, max_length=20, null=True, validators=[main.models.final_score_validation], verbose_name='Итоговый счет')),
                ('date', models.DateField(verbose_name='Дата')),
                ('weather', models.CharField(blank=True, max_length=30, null=True, validators=[main.models.weather_validation], verbose_name='Погода')),
                ('opponent', models.CharField(max_length=100, verbose_name='Соперник')),
                ('is_played', models.BooleanField(verbose_name='Завершен')),
                ('football_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main.footballclub', verbose_name='Футбольный клуб')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.AddField(
            model_name='footballclub',
            name='stadium',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.stadium', verbose_name='Стадион'),
        ),
        migrations.AddField(
            model_name='footballclub',
            name='statistics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.teamstatistics', verbose_name='Статистика команды'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('age', models.IntegerField(validators=[main.models.age_range_validation], verbose_name='Возраст')),
                ('nationality', models.CharField(max_length=50, verbose_name='Национальность')),
                ('additional_data', models.TextField(blank=True, max_length=500, null=True, verbose_name='Дополнительные сведения')),
                ('post', models.CharField(max_length=50, verbose_name='Пост')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Веб сайт')),
                ('team_tactics', models.CharField(blank=True, max_length=50, null=True, validators=[main.models.team_tactics_validation], verbose_name='Тактика')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.contract', verbose_name='Контракт')),
                ('football_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='main.footballclub', verbose_name='Футбольный клуб')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
            },
        ),
    ]
