# Generated by Django 3.1.7 on 2021-04-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210416_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Амплуа'),
        ),
    ]
