# Generated by Django 3.1.7 on 2021-04-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210426_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='openning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Открытия'),
        ),
    ]
