# Generated by Django 3.1.7 on 2021-04-23 19:45

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210422_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(validators=[main.models.age_range_validation], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='age',
            field=models.IntegerField(validators=[main.models.age_range_validation], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='team_tactics',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[main.models.team_tactics_validation], verbose_name='Тактика'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.IntegerField(validators=[main.models.salary_range_validation], verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='match',
            name='final_score',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[main.models.final_score_validation], verbose_name='Итоговый счет'),
        ),
        migrations.AlterField(
            model_name='match',
            name='weather',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[main.models.weather_validation], verbose_name='Погода'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(validators=[main.models.age_range_validation], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True, validators=[main.models.height_range_validation], verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(validators=[main.models.shirt_number_range_validation], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[main.models.weight_range_validation], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(validators=[main.models.capacity_range_validation], verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='place',
            field=models.IntegerField(validators=[main.models.place_range_validation], verbose_name='Место в таблице'),
        ),
    ]
