# Generated by Django 3.1.7 on 2021-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210426_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstatistics',
            name='place',
            field=models.IntegerField(verbose_name='Место в таблице'),
        ),
    ]
