# Generated by Django 3.1.7 on 2021-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210426_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
    ]
