# Generated by Django 3.1.7 on 2021-04-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210427_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
