# Generated by Django 3.1.7 on 2021-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210427_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='minutes_played',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество сыгранных минут'),
        ),
    ]
