# Generated by Django 3.1.7 on 2021-04-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210427_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_from_academy',
            new_name='is_local',
        ),
    ]
