# Generated by Django 3.1.7 on 2021-04-26 19:56

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210427_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(validators=[main.models.age_range_validation], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='age',
            field=models.IntegerField(validators=[main.models.age_range_validation], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.IntegerField(validators=[main.models.salary_range_validation], verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='stadium',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.stadium', verbose_name='Стадион'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(validators=[main.models.age_range_validation], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True, validators=[main.models.height_range_validation], verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(validators=[main.models.shirt_number_range_validation], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[main.models.weight_range_validation], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='place',
            field=models.IntegerField(validators=[main.models.place_range_validation], verbose_name='Место в таблице'),
        ),
    ]
