# Generated by Django 3.1.7 on 2021-04-27 15:18

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210427_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='matches_played',
            field=models.IntegerField(validators=[main.models.validate_matches_played], verbose_name='Сыграно матчей'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='draws',
            field=models.IntegerField(validators=[main.models.validate_draws], verbose_name='Ничьи'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='loses',
            field=models.IntegerField(validators=[main.models.validate_loses], verbose_name='Поражения'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='matches_played',
            field=models.IntegerField(validators=[main.models.validate_matches_played], verbose_name='Сыграно матчей'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='wins',
            field=models.IntegerField(validators=[main.models.validate_wins], verbose_name='Победы'),
        ),
    ]
