# Generated by Django 3.1.7 on 2021-05-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210507_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
    ]
