# Generated by Django 3.1.7 on 2021-05-07 18:16

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210508_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(blank=True, null=True, validators=[main.models.shirt_number_range_validation], verbose_name='Номер'),
        ),
    ]
