# Generated by Django 3.1.7 on 2021-05-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210508_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contract', verbose_name='Контракт'),
        ),
        migrations.AlterField(
            model_name='player',
            name='football_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.footballclub', verbose_name='Футбольный клуб'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_foreign',
            field=models.BooleanField(blank=True, null=True, verbose_name='Легионер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_local',
            field=models.BooleanField(blank=True, null=True, verbose_name='Воспитанник клуба'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Амплуа'),
        ),
        migrations.AlterField(
            model_name='player',
            name='statistics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.playerstatistics', verbose_name='Статистика игрока'),
        ),
    ]
