# Generated by Django 3.1.7 on 2021-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210508_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='first_name',
            field=models.CharField(blank=True, default='John', max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(blank=True, default='Doe', max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='first_name',
            field=models.CharField(blank=True, default='John', max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_name',
            field=models.CharField(blank=True, default='Doe', max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, default='John', max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, default='Doe', max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
