# Generated by Django 3.1.7 on 2021-05-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210508_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclub',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
