# Generated by Django 3.1.7 on 2021-05-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210509_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.contract', verbose_name='Контракт'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='football_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='main.footballclub', verbose_name='Футбольный клуб'),
        ),
    ]
