# Generated by Django 3.1.7 on 2021-05-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210510_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='football_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main.footballclub', verbose_name='Футбольный клуб'),
        ),
    ]
