# Generated by Django 3.1.7 on 2021-05-10 08:20

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210510_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='assists',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голевые передачи'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='red_cards',
            field=models.IntegerField(blank=True, null=True, verbose_name='Красные карточки'),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='yellow_cards',
            field=models.IntegerField(blank=True, null=True, verbose_name='Желтые карточки'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='draws',
            field=models.IntegerField(blank=True, null=True, validators=[main.models.validate_draws], verbose_name='Ничьи'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='goals_conceded',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пропущенные голы'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='loses',
            field=models.IntegerField(blank=True, null=True, validators=[main.models.validate_loses], verbose_name='Поражения'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='red_cards',
            field=models.IntegerField(blank=True, null=True, verbose_name='Красные карточки'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='wins',
            field=models.IntegerField(blank=True, null=True, validators=[main.models.validate_wins], verbose_name='Победы'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='yellow_cards',
            field=models.IntegerField(blank=True, null=True, verbose_name='Желтые карточки'),
        ),
    ]
